# methods on list
lst=[45,50,"hello",3.14,True,"hai"]
print(lst)
print(len(lst))
lst .append("world")
print(lst)
lst.extend([1,2,3])
print("the extended list is ",lst)
lst.insert(1,"a")
print(lst)
lst.remove("world")
print(lst)
lst.pop()
print(lst)
lst.pop(1)
print(lst)
t=lst.copy()
print(t)
t.clear()
print(t)
p=lst.index(3.14)
print(p)
c=lst.count(45)
print(c)
print(lst)
lst.reverse()
print(lst)
